# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://leifengblog.net"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: LeiFengBlog

# Short description of your site
description: Lei Feng's Blog

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Home: "/"
  Archives:
   - Categories: "/archives/categories"
   - Tags: "/archives/tags"
  About: "/about/"
  
  
# where are the tags and categories pages
tag_page: "/archives/tags"
category_page: "/archives/categories"
 
 #   - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
 #   - Learn markdown: "http://www.markdowntutorial.com/"
#    - GitHub Pages: "https://pages.github.com/"


# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar/leifeng02.jpg"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Lei Feng
  email: lfengstone@gmail.com
  facebook: stonefl  # eg. daattali
  github: stonefl    # eg. daattali
  twitter: MicroFeng   # eg. daattali
  linkedin: "in/leifeng1"  # eg. "pub/dean-attali/8/946/143"
  stackoverflow: yourlink  # eg. "3943160/daattali"
 
# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: true
  email: true
  twitter: true
  github: true
  linkedin: true
  stackoverflow: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "leifengblog.net"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "stonefl-github-io"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-81659112-1"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
markdown: kramdown
#highlighter: rouge
permalink: /blog/:title/
paginate: 5
excerpt_separator: <!--more-->

# turning on recognition of GitHub Flavored Markdown and syntx highlighting
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: "" # all files in the project 
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts' # restrict authoring access to a directory
  ignore:  # Array of files to ignore and hide in Prose
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  #siteurl: "https://stonefl.github.io/" # turns on Jekyll live preview
  media: 'img' # specify a media directory uploading images defaults to.
  metadata: # front matter settings
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Choose Category"
          options:
           - name: "Programming"
             value: "Programming"
           - name: "Operations Research"
             value: "Operations Research"
           - name: "Algorithms"
             value: "Algorithms"
           - name: "Data Structure"
             value: "Data Structure"
           - name: "Machine Learning"
             value: "Machine Learning"
          alterable: true
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
           - name: "Java"
             value: "Java"
           - name: "Python"
             value: "Python"
          alterable: true
gems:
  - jekyll-paginate

